// Shared TypeScript types for Cursive

export interface Point {
  x: number;
  y: number;
  pressure?: number; // For pressure sensitivity
  timestamp?: number; // For gesture detection (speed calculation)
}

export interface Stroke {
  points: Point[];
  color: string;
  width: number;
  timestamp?: number;
  // Educational integrity
  isAI?: boolean;            // TRUE if generated by AI (for hide/show toggle)
  // Training metadata (optional)
  character?: string;        // What letter/character is this?
  strokeOrder?: number;      // Which stroke in the character (1st, 2nd, etc.)
  position?: 'start' | 'middle' | 'end';  // Position in word
  connectedTo?: string;      // Next character if cursive
  normalized?: boolean;      // Has this been normalized to guides?
}

export type Tool = 'draw' | 'select' | 'pan' | 'zoom' | 'lasso';

export interface SelectionRect {
  startX: number;
  startY: number;
  endX: number;
  endY: number;
}

// Text overlay (for AI responses on canvas)
export interface TextOverlay {
  id: string;
  text: string;
  x: number;
  y: number;
  width: number;
  fontSize: number;
  color: string;
  timestamp: number;
  isAI?: boolean;  // TRUE if generated by AI (for hide/show toggle)
}

// Typography guides (for handwriting training)
export interface TypographyGuides {
  enabled: boolean;
  baseline: number;        // Y-coordinate where letters sit
  xHeight: number;         // Height of lowercase letters (e.g., 'x')
  capHeight: number;       // Height of capital letters
  ascender: number;        // Top line (for b, d, h, k, l, t)
  descender: number;       // Bottom line (for g, j, p, q, y)
  color: string;          // Color of guide lines
  opacity: number;        // 0-1, how visible the guides are
}

// Training mode state
export interface TrainingMode {
  active: boolean;
  currentPrompt: string;   // "Write the letter 'a'"
  currentCharacter: string; // 'a'
  samplesRequired: number;  // How many samples to collect
  samplesCollected: number; // How many we have so far
  style: 'print' | 'cursive'; // Writing style
}

// Page system (A4-sized pages in notebook)
export interface Page {
  id: string;
  notebookId: string;
  pageNumber: number;       // 1, 2, 3, etc.
  title?: string;           // Optional title: "Intro to Derivatives", "Practice Problems"
  size: 'A4' | 'Letter' | 'A5';
  orientation: 'portrait' | 'landscape';
  backgroundColor: string;
  createdAt: number;
  updatedAt: number;
}

// Bounding box for spatial calculations
export interface BoundingBox {
  x: number;
  y: number;
  width: number;
  height: number;
  type?: 'student_stroke' | 'ai_response' | 'selection';
}

// Spatial context sent to AI for intelligent response positioning
export interface SpatialContext {
  pageSize: {
    width: number;   // e.g., 794 for A4
    height: number;  // e.g., 1123 for A4
  };
  selectionBounds: BoundingBox;
  occupiedRectangles: BoundingBox[];  // All existing content on page
  suggestedResponseY: number;         // Where AI should start writing
  availableSpaceBelow: number;        // Space between selection and occupied content below
}

// Lasso selection (closed path with selected strokes)
export interface LassoSelection {
  path: Point[];              // The lasso path itself
  selectedStrokes: number[];  // Indices of strokes within lasso
  bounds: BoundingBox;        // Bounding box of selection
  pageId: string;             // Which page this selection is on
}

// Multi-page send context (for sending pages 2-4 together)
export interface MultiPageSendContext {
  primaryPageId: string;      // The page where lasso was drawn
  includePageIds: string[];   // Additional pages to include
  selectionBounds?: BoundingBox; // Optional: bounds of lasso selection
}

export interface CanvasState {
  // Tool state
  currentTool: Tool;

  // Page system
  pages: Page[];
  currentPageId: string;

  // Drawing state
  drawings: Stroke[];
  currentStroke: Point[];

  // Transform state
  scale: number;
  panX: number;
  panY: number;

  // Selection state
  selectionRect: SelectionRect | null;
  lassoSelection: LassoSelection | null;

  // Chat/Conversation state
  chatHistory: ChatMessage[];
  textOverlays: TextOverlay[];

  // Educational integrity
  hideAIResponses: boolean;

  // Training mode
  typographyGuides: TypographyGuides;
  trainingMode: TrainingMode;

  // History
  undoStack: Stroke[][];
  redoStack: Stroke[][];
}

export interface CanvasActions {
  // Tool actions
  setTool: (tool: Tool) => void;

  // Page actions
  addPage: () => void;
  deletePage: (pageId: string) => void;
  goToPage: (pageId: string) => void;
  nextPage: () => void;
  previousPage: () => void;
  updatePageTitle: (pageId: string, title: string) => void;

  // Drawing actions
  startDrawing: (point: Point) => void;
  continueDrawing: (point: Point) => void;
  finishDrawing: () => void;

  // Selection actions (rectangular)
  startSelection: (x: number, y: number) => void;
  updateSelection: (x: number, y: number) => void;
  finishSelection: () => ImageData | null;
  clearSelection: () => void;

  // Lasso actions
  startLasso: (point: Point) => void;
  continueLasso: (point: Point) => void;
  finishLasso: () => void;
  clearLasso: () => void;
  setLassoSelection: (selection: LassoSelection | null) => void;
  setLastAITimestamp: (timestamp: number) => void;
  sendLassoToAI: (includePageIds?: string[]) => Promise<void>;

  // Pan actions
  startPan: (x: number, y: number) => void;
  updatePan: (x: number, y: number) => void;
  finishPan: () => void;

  // Zoom actions
  zoom: (delta: number, centerX: number, centerY: number) => void;

  // Chat/Conversation actions
  addChatMessage: (message: ChatMessage) => void;
  addTextOverlay: (overlay: TextOverlay) => void;
  removeTextOverlay: (id: string) => void;
  clearTextOverlays: () => void;

  // Educational integrity actions
  toggleHideAIResponses: () => void;

  // Typography & Training actions
  toggleTypographyGuides: () => void;
  updateTypographyGuides: (guides: Partial<TypographyGuides>) => void;
  startTrainingMode: (style: 'print' | 'cursive') => void;
  stopTrainingMode: () => void;
  nextTrainingPrompt: () => void;
  submitTrainingSample: (stroke: Stroke) => void;

  // History actions
  undo: () => void;
  redo: () => void;

  // Utility actions
  clearAll: () => void;
  getCanvasImageData: () => ImageData | null;
}

// Chat types
export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: number;
  isHandwritten?: boolean;
}

export interface TranscriptionResult {
  transcription: string;
  tags: string[];
}
